AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-authorizer

  Sample SAM Template for lambda-authorizer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java11
    Architectures:
      - x86_64
    MemorySize: 512
    Environment:
      Variables:
        PHOTO_APP_USERS_POOL_ID: us-east-1_jB6GkcuFp
        PHOTO_APP_USERS_APP_CLIENT_ID: v76tpt19vvkee61ara5j9po12

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: open-api.yaml
  GetUserByUsernameHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LambdaAuthorizer
      Handler: com.appsdeveloperblog.aws.lambda.GetUserByUsernameHandler::handleRequest
      Events:
        GetUserByUsername:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users/{userName}
            Method: get
            RestApiId:
              Ref: MyApi
  LambdaAuthorizerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LambdaAuthorizer
      Handler: com.appsdeveloperblog.aws.lambda.authorizer.LambdaAuthorizer::handleRequest
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetUserByUsernameApi:
    Description: "API Gateway endpoint URL for Prod stage for Get User by Username function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users"
  GetUserByUsernameHandlerFunction:
    Description: "Get User by Username Function ARN"
    Value: !GetAtt GetUserByUsernameHandlerFunction.Arn
  GetUserByUsernameHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for Get User by Username function"
    Value: !GetAtt GetUserByUsernameHandlerFunctionRole.Arn
